title: anagha tiwari
description: computer science phd student @ uchicago
url: "https://anaghatiwari.github.io"
theme: minima
plugins:
- jekyll-remote-theme

# Social links
github_username: anaghatiwari
linkedin_username: anagha-tiwari1
email: anaghatiwari@uchicago.edu

# Navigation links (these will show in sidebar)
show_downloads: false

# Build settings
markdown: kramdown
